### ISSUE TITLE
"Type message to channel" box

### ISSUE THREAD

**Issue by funkydude** [mumble-voip/mumble-theme#2]
The box where text is typed should be white in the new theme. As it stands it just looks like some text on a background, whereas it should look like a separated area.

**Comment by xPoke** [comment]
This is an old style choice I made which over time grew on me (it's added as a special case for text boxes). I see the issues with it and will probably make this change if I don't find another option.
The reasons were:
1. Both other "objects" in the main window are not text boxes - but they look similar in decoration to all other boxes. This can cause some confusion (one of the boxes is a text input field while the other are a text output box and a tree view box). In more complex styles it's easy to tell the difference, but when all objects are plain with simple borders, I wanted to give it a different style.
2. The main window has a slightly different style from the other windows (it has lots of border-less floating elements), which is more similar to the style I was going for. The other windows got more old-fashioned controls because the whole layout couldn't be changed completely, and they are full of elements difficult to show in border-less "flat" UIs (combo boxes, spin boxes, tables with inner elements)

One reason was for usability and the second for esthetics. Both of which are probably less important than consistency. I will try a few other approaches and see if anything sticks, but if not, I'll probably remove the special styling on the main window text box.

**Comment by xPoke** [comment]
See https://github.com/mumble-voip/mumble-theme/commit/f26a0234c35c9c1b6bf5c6e847bff11171bedb5e

**Comment by funkydude** [comment]
This issue is fixed now and can be closed.
